-- MySQL Script generated by MySQL Workbench
-- Mon Jul 25 21:52:31 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`User`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`User` (
  `idUser` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(100) NOT NULL,
  `tipo_user` VARCHAR(1) NOT NULL,
  `senha` VARCHAR(45) NOT NULL,
  `faculdade` VARCHAR(45) NULL,
  `idade` DATE NULL,
  PRIMARY KEY (`idUser`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Publicacao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Publicacao` (
  `idPublicacao` INT NOT NULL AUTO_INCREMENT,
  `nome_prof` VARCHAR(45) NOT NULL,
  `email_prof` VARCHAR(45) NULL,
  `titulo` VARCHAR(30) NULL,
  `descricao` VARCHAR(280) NOT NULL,
  `ministrou_disciplina` VARCHAR(1) NULL,
  `like` INT NULL,
  `User_idUser` INT NOT NULL,
  PRIMARY KEY (`idPublicacao`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Comentario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Comentario` (
  `idComentario` INT NOT NULL AUTO_INCREMENT,
  `descricao` VARCHAR(180) NOT NULL,
  `Publicacao_idPublicacao` INT NOT NULL,
  `User_idUser` INT NOT NULL,
  PRIMARY KEY (`idComentario`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`FAQ`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`FAQ` (
  `idFAQ` INT NOT NULL AUTO_INCREMENT,
  `descricao` VARCHAR(280) NOT NULL,
  `User_idUser` INT NOT NULL,
  PRIMARY KEY (`idFAQ`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`PROF_UNI`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`PROF_UNI` (
  `idProf_Uni` INT NOT NULL,
  `nome_prof` VARCHAR(45) NULL,
  `nome_uni` VARCHAR(45) NULL,
  `User_idUser` INT NOT NULL,
  PRIMARY KEY (`idProf_Uni`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
